version: '3.8'

services:

  kafka:
    image: apache/kafka:latest
    container_name: fraud_kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - fraud_network

  redis:
    image: redis:alpine
    container_name: fraud_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fraud_network

  minio:
    image: minio/minio:latest
    container_name: fraud_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - fraud_network

  grafana:
    image: grafana/grafana:latest
    container_name: fraud_grafana
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - fraud_network

networks:
  fraud_network:
    driver: bridge

volumes:
  kafka_data:
  redis_data:
  minio_data:
  grafana_data: